HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 29 Oct 2014 16:46:48 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept
X-Frame-Options: SAMEORIGIN
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS

[
    "token",
    "Some other token",
    "bananas",
    {"subobj": 4}
]
