HTTP/1.1 400 BAD REQUEST
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 07 Oct 2014 21:42:50 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN
Allow: POST, OPTIONS

{"detail": "No account for that email address"}